# Jekyll configuration

name: SharkLib
description: Welcome to SharkLib

# url is currently only used only for the RSS feed in feed.xml
url: https://github.com/SharkLib

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: ''
## default date_format
date_format: 
  title: "%B-%-d-%Y"
  archive: "%b"
  categories: "%b-%Y"
  tag: "%b-%Y"
# Language
lan: "en" 


# Remove the item if you don't need it
github_username: sharklib
facebook_username: facebook_username
twitter_username: ronghuang100
instagram_username: ronghuang100
linkedin_username: rong-huang-61751047
medium_username: ronghuang100

paginate: 10

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE', "*.bak"]
